### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by slota** [shyiko/amqplib-auto-recovery#2]
I believe this shouldn't be happening with auto recovery, when we run our program and rabbitmq is not up we get this issue with auto recovery
 
```
AMQP error Error: Channel ended, no reply will be forthcoming
    at rej (/Users/localadmin/workspace/nautilus-js/node_modules/amqplib/lib/channel.js:190:7)
    at Channel.C._rejectPending (/Users/localadmin/workspace/nautilus-js/node_modules/amqplib/lib/channel.js:196:42)
    at Channel.C.toClosed (/Users/localadmin/workspace/nautilus-js/node_modules/amqplib/lib/channel.js:160:8)
    at Channel.C.accept (/Users/localadmin/workspace/nautilus-js/node_modules/amqplib/lib/channel.js:411:10)
    at Connection.mainAccept [as accept] (/Users/localadmin/workspace/nautilus-js/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/Users/localadmin/workspace/nautilus-js/node_modules/amqplib/lib/connection.js:476:48)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:433:10)
    at emitReadable (_stream_readable.js:427:7)
    at readableAddChunk (_stream_readable.js:188:13)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)```

**Comment by shyiko** [comment]
Hi @slota. Any chance you could provide an example to demonstrate the failure? I don't see amqplib-auto-recovery anywhere in that stack trace. Chances are it's misconfiguration issue.

**Comment by slota** [comment]
Our code is below, we call the auto recovery and them pass in an array of services where we connect each one to rabbit. We are trying to simulate rabbitmq not being up, and having it continue to try to reconnect
```
function main(){
  return withAutoRecovery(amqp, {}).connect(rabbitUrl(), connectToRabbitMQ)
}

function connectToRabbitMQ(err, conn){
  if (err) {
    console.error("AMQP: ", err.message);
    return
  }

  conn.on("error", function(err){
    if (err.message !== "Connection closing") {
      console.error("AMQP conn error", err.message);
      return
    }
  });

  conn.on("close", function() {
    console.error("AMQP: reconnecting");
    return
  });

  console.log("AMQP: connected");
  whenConnected(conn);
}
```
```
function whenConnected(conn) {
  var services = serviceList.services;
  services.forEach(function(service, index){
    subscribeToService(service, conn);
  });
}

function subscribeToService(service, conn){
  connection = conn
  conn.createChannel(function(err, ch){
    if (closeOnErr(err)) return;
    ch.on("error", function(err){
      console.error("AMQP channel error", err.message);
    });

    ch.on("close", function() {
      console.log("[AMQP] channel closed");
      return
    });
    ch.checkExchange(service);
    ch.service = service
    URLS[service];
    ch.assertQueue("", {exclusive: true}, function(err, q){
      if (closeOnErr(err)) return;
      ch.bindQueue(q.name, service, "");
      ch.consume(q.name, processMsg, {noAck: false});
      console.log("Channel:", service);
    });

    function processMsg(msg) {
      work(msg, function(ok) {
        try {
          if (ok)
          URLS[ch.service] = msg.content.toString()
          else
          ch.reject(msg, true);
        } catch (e) {
          closeOnErr(e);
          return
        }
      });
    }
  });
}
```

**Comment by slota** [comment]
So there are no exchanges that are created...

**Comment by slota** [comment]
Ok I think I understand the problem now, we had rabbitmq running but we did not create the exchanges. This broke it. I killed RabbitMQ and now it is trying to reconnect as expected. Thank you so much!!
